import './globals.css'
import type { Metadata } from 'next'
import Providers from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
      <body style={{
        height: '100vh'
      }}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
